### ISSUE TITLE
需要增添

### ISSUE THREAD

**Issue by kurisucat** [MisaLiu/Evil_Xiaojie#2]
在 _在倾诉的过程中，另一位用户兼好友rpONE（该用户在年初就因为所谓”违规”被小杰移出群）表示愤愤不平，扬言“将会DDoS攻击小杰的服务器”（事后多方求证，小杰服务器并非rpONE所攻击，而是另一位技术人员被收钱指使所为）。其他群员也尽量使Kurisu冷静下来。_
后面添加：**Kurisu 表示：禁言三天为“全全”所为，全局拉黑和移除QQ群为小杰所为。
后面的一段时间，小杰同步了所有关于小米公司的“小爱”及“小爱”相关产品及内测群的机器人，使之 Kurisu 被移出了所有关于小米公司的“小爱”及“小爱”相关产品及内测群。**

**Comment by MisaLiu** [comment]
已修改，感谢反馈。
