### ISSUE TITLE
请问这是真实有效吗

### ISSUE THREAD

**Issue by museed** [MisaLiu/Evil_Xiaojie#3]

**Comment by museed** [comment]
我想说的是。需要实事求是的

**Comment by MisaLiu** [comment]
我们在编写 README.MD 时尽量保证能做到全面看事件，并能找到相关证据(如截图)

如果您认为有部分内容不真实，欢迎您指出并提is。

**Comment by museed** [comment]
我想加入你们该如何加入你们？

**Comment by MisaLiu** [comment]
已经向您的邮箱发布了一个邀请邮件，请注意查收。
