### ISSUE TITLE
如内容

### ISSUE THREAD

**Issue by kurisucat** [MisaLiu/Evil_Xiaojie#5]
> 建议在此处做补充：Kurisu 表示，他并没有放弃交涉，由于学业原因而没有时间处理这件事情。

Kurisu 表示，在 2020 年 3 月至 6 月（时间可能更新不够及时）以来并 Kurisu 没有放弃交涉（以间接或直接的向小米小爱老师官方人员反馈），由于学业原因而没有时间处理来频繁的这件事情。

**Comment by MisaLiu** [comment]
已收到，正在修改
